version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hathat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elhathatdb
      MYSQL_USER: elhathatmed
      MYSQL_PASSWORD: hathat1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
